name: "Run Container Scan on Super Mario Docker Image with Quality Gate"

on:
  push:
    branches:
      - main

jobs:

  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Docker image version properly
      - name: Docker Image version
        run: |
          VERSION=$(( $(cat version.txt) + 1 ))
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Pull Docker Image
        run: |
          docker pull kasshichem/supermariogitopsproject:${{ env.VERSION }}

      # Scan directly (no tar needed)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: kasshichem/supermariogitopsproject:${{ env.VERSION }}
          severity: CRITICAL,HIGH
          exit-code: '0'